-- MySQL Script generated by MySQL Workbench
-- Fri Oct  9 23:46:52 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_web_dtell
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_web_dtell
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_web_dtell` DEFAULT CHARACTER SET utf8 ;
USE `db_web_dtell` ;

-- -----------------------------------------------------
-- Table `db_web_dtell`.`autos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_web_dtell`.`autos` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL DEFAULT NULL,
  `fecha_auto` DATE NOT NULL,
  `foto` VARCHAR(255) NULL DEFAULT NULL,
  `marca` VARCHAR(255) NULL DEFAULT NULL,
  `modelo` VARCHAR(255) NULL DEFAULT NULL,
  `nombre` VARCHAR(12) NOT NULL,
  `placa` VARCHAR(255) NULL DEFAULT NULL,
  `precio` FLOAT NOT NULL,
  `tipo_auto` VARCHAR(255) NULL DEFAULT NULL,
  `tipo_combustible` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_web_dtell`.`distritos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_web_dtell`.`distritos` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_web_dtell`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_web_dtell`.`clientes` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `apellido` VARCHAR(255) NULL DEFAULT NULL,
  `direccion` VARCHAR(255) NULL DEFAULT NULL,
  `dni` VARCHAR(8) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `fechacliente` DATE NOT NULL,
  `foto` VARCHAR(255) NULL DEFAULT NULL,
  `nombre` VARCHAR(12) NOT NULL,
  `ruc` VARCHAR(255) NULL DEFAULT NULL,
  `telefono` VARCHAR(9) NULL DEFAULT NULL,
  `distrito_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKsdbo38w2cj7keqa05x3vqcsw6` (`distrito_id` ASC),
  CONSTRAINT `FKsdbo38w2cj7keqa05x3vqcsw6`
    FOREIGN KEY (`distrito_id`)
    REFERENCES `db_web_dtell`.`distritos` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_web_dtell`.`facturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_web_dtell`.`facturas` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL DEFAULT NULL,
  `fecha_alquiler` DATE NULL DEFAULT NULL,
  `observacion` VARCHAR(255) NULL DEFAULT NULL,
  `cliente_id` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK1qiuk10rfkovhlfpsk7oic0v8` (`cliente_id` ASC),
  CONSTRAINT `FK1qiuk10rfkovhlfpsk7oic0v8`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `db_web_dtell`.`clientes` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_web_dtell`.`facturas_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_web_dtell`.`facturas_items` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `cantidad` INT(11) NULL DEFAULT NULL,
  `auto_id` BIGINT(20) NULL DEFAULT NULL,
  `factura_id` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKhi9yfjvuj8nc86nuo3m75oi5i` (`auto_id` ASC),
  INDEX `FKnv8ijya20df661b0p6drqcx7u` (`factura_id` ASC),
  CONSTRAINT `FKhi9yfjvuj8nc86nuo3m75oi5i`
    FOREIGN KEY (`auto_id`)
    REFERENCES `db_web_dtell`.`autos` (`id`),
  CONSTRAINT `FKnv8ijya20df661b0p6drqcx7u`
    FOREIGN KEY (`factura_id`)
    REFERENCES `db_web_dtell`.`facturas` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
